--     MERGE INTO APPLICATION_USER T USING (VALUES(1,'$2a$10$kkNFpm82ifKNT87up1fG8uUebRBIuyWcfRC/vVfs/mfjeeuAhE9dO', TRUE,'Admin User',null,'Admin'))S(ID, HASHED_PASSWORD,ISDARKMODE,NAME,PROFILE_PICTURE,USERNAME)ON T.USERNAME = S.USERNAME WHEN NOT MATCHED THEN INSERT (ID, HASHED_PASSWORD,ISDARKMODE,NAME,PROFILE_PICTURE,USERNAME) VALUES (S.ID, S.HASHED_PASSWORD,S.ISDARKMODE,S.NAME,S.PROFILE_PICTURE,S.USERNAME);
    INSERT INTO `application_user` (id,`name`,`username`,`hashed_password`) SELECT * FROM (SELECT 1,'admin','Admin','$2a$10$hMwxZydsskP4si0E13/5Uupd.y5MjpeKC2JD1SJsyHgR7mzWcW.6W') AS new_value WHERE NOT EXISTS (SELECT name FROM `application_user`) LIMIT 1;
    MERGE INTO USER_ROLES T USING (VALUES(1,'ADMIN') ) S(USER_ID,ROLES) ON T.USER_ID = S.USER_ID  AND T.ROLES = S.ROLES WHEN NOT MATCHED THEN INSERT (USER_ID,ROLES)VALUES (S.USER_ID,S.ROLES);
--     MERGE INTO USER_ROLES T USING (VALUES(1,'USER') ) S(USER_ID,ROLES) ON T.USER_ID = S.USER_ID  AND T.ROLES = S.ROLES WHEN NOT MATCHED THEN INSERT (USER_ID,ROLES)VALUES (S.USER_ID,S.ROLES);
--     INSERT INTO `application_user` (id,`name`,`username`,`hashed_password`) SELECT * FROM (SELECT 1,'admin','admin_user','$2a$10$hMwxZydsskP4si0E13/5Uupd.y5MjpeKC2JD1SJsyHgR7mzWcW.6W') AS new_value WHERE NOT EXISTS (SELECT name FROM `application_user`) LIMIT 1;
--     INSERT INTO `user_roles` (user_id,`roles`) SELECT * FROM (SELECT 1,'ADMIN') AS new_value WHERE NOT EXISTS (SELECT * FROM `user_roles` WHERE roles = ADMIN) LIMIT 1;

    MERGE INTO EMAIL_SETTING E USING (VALUES(1)) S(ID) ON E.ID = S.ID WHEN NOT MATCHED THEN INSERT (ID,Pop3Host,Pop3Port,SMTP_Auth,SMTP_from,SMTP_host,SMTP_port,SMTP_Start_TLS_Req,SMTP_StartTLS_Enable,user_name,user_password) VALUES (1,'', 995,TRUE,'','',587,TRUE,TRUE,'','');
    MERGE INTO ENGINEER E USING (VALUES(1)) S(ID) ON E.ID = S.ID WHEN NOT MATCHED THEN INSERT (ID,forename,lastname,email) VALUES (1,'Select','Engineer','default@gmail.com');
    MERGE INTO SETTING E USING (VALUES(1)) S(ID) ON E.ID = S.ID WHEN NOT MATCHED THEN INSERT (ID,Auto_Backup,Auto_Update_Sites,Backup_Path,Backup_time,Cylon_Path,Update_Sites_time) VALUES (1,'true','false','C:\Backup','5:00','C:\UnitronUC32','3:00');


